{% set name = "pyrodigal" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/78/a7/9e656b131bc946a32ba2b4ca193fa3b9afbac36d845c80743cfd92df08f3/pyrodigal-1.1.0.tar.gz
  sha256: bc8858408bdf0cb0be76698b8ab73439a64a0956d8e747950780ab8eaa82caad

build:
  number: 0
  skip: True  #[py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - {{ name }}
  commands:
    - python -m unittest -vv {{ name }}.tests

about:
  home: https://github.com/althonos/pyrodigal
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: Python bindings to Prodigal, an ORF finder for microbial sequences.
  doc_url: https://pyrodigal.readthedocs.org/

extra:
  recipe-maintainers:
    - althonos
  identifiers:
    - doi:10.21105/joss.04296  # JOSS paper
