{% set name = "ggCaller" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/samhorsfield96/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 896184addbcf1446f74a5844651f36c6dc43a9e59df6f998c32976cd35706f61

build:
  number: 0
  skip: False  # [osx or py < 38]
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ggcaller = ggCaller.__main__:main

requirements:
  build:
    - {{ compiler('c')}}
    - {{ compiler('cxx') }}
    - cmake >=3.10
    - make
    - setuptools
    - llvm-openmp  # [osx]
    - libgomp      # [linux64]
    - boost-cpp
    - eigen =3.3
    - pytorch
    - python >=3.9
  host:
    - python >=3.9
    - pybind11
    - bifrost
    - pthread-stubs
    - zlib
    - pip
    - bzip2
  run:
    - python >=3.9
    - bx-python
    - numpy
    - scipy
    - pandas
    - bifrost
    - biopython
    - bcbio-gff >=0.6.9
    - diamond
    - hmmer
    - mafft
    - snp-sites
    - zlib
    - pytorch
    - pthread-stubs
    - matplotlib-base
    - xorg-libxi
    - xorg-libxcursor
    - xorg-libxdamage
    - xorg-libxcomposite
    - xorg-libxrandr
    - xorg-libxinerama
    - xorg-libxpm
    - xorg-libxaw
    - xorg-libxfixes
    - intbitset
    - networkx
    - uncertainties
    - eigen =3.3
    - openblas
    - cmake >=3.10
    - libgomp
    - llvm-openmp
    - tqdm
    - setuptools
    - make
    - seaborn
    - rapidnj
    - tbb-devel
    - python-edlib >=1.3
    - joblib
    - gffutils
    - cd-hit
    - python-wget

test:
  imports:
    - ggCaller_cpp
    - ggCaller
    - panaroo_runner
  commands:
    - ggcaller -h | grep -q "Generates ORFs from a Bifrost graph."

about:
   home: https://github.com/samhorsfield96/ggCaller
   license: MIT
   license_file: LICENSE
   summary: 'a gene caller for Bifrost graphs'
