package:
  name: perl-metabolomics-fragment-annotation
  version: "0.6.6"

source:
  url: https://cpan.metacpan.org/authors/id/G/GI/GIACOMONI/Metabolomics-Fragment-Annotation-0.6.6.tar.gz
  sha256: 847163817d2b9a52c30b5896e6c0d0f85321122c53365f786e456f632ce1e850

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl
    - perl-file-share
    - perl-text-csv
    - perl-text-csv_xs
    - perl-xml-twig
    - perl-file-sharedir-install
    - perl-json
    - perl-html-template
    - perl-uri
    - perl-log-any
    - perl-datetime
    - perl-lwp-protocol-https

  run:
    - perl
    - perl-file-share
    - perl-text-csv
    - perl-text-csv_xs
    - perl-xml-twig
    - perl-file-sharedir-install
    - perl-json
    - perl-html-template
    - perl-uri
    - perl-log-any
    - perl-datetime
    - perl-lwp-protocol-https

test:
  # Perl 'use' tests
  imports:
    - Metabolomics::Fragment::Annotation

about:
  home: https://metacpan.org/pod/Metabolomics::Fragment::Annotation
  license: perl_5
  summary: 'Perl extension for fragment annotation in metabolomics'
