package:
  name: logol
  version: "1.7.9"

build:
  number: 0
  detect_binary_files_with_prefix: False
  skip: True # [not linux]

source:
  url: https://github.com/genouest/logol/archive/1.7.9.tar.gz
  sha256: 239aa703f7b7f1ff2917e53681ee30be6211344f8eaf0f207e555db49c71956b

requirements:
  build:
    - {{ compiler('c') }}
    - ant
    - antlr
  host:
    - ruby >=2.4
    - cassiopee
    - openjdk
    - swi-prolog
  run:
    - ruby >=2.4
    - cassiopee
    - openjdk
    - swi-prolog

test:
  commands:
    - LogolMultiExec.sh -h
    - LogolExec.sh -h

about:
  home: https://github.com/genouest/logol
  license: Affero GPL 3.0
  license_file: LICENSE.txt
  summary: Logol is a pattern matching grammar language and a set of tools to search a pattern in a sequence (nucleic or proteic)
