{% set version = "1.1.4b" %}
{% set sha256 = "9a25293ad4f6afa1e8cb630ee040fd985e7fe0d2cdde3dd01f3af486614ad6ef" %}

package:
  name: bigscape
  version: {{ version }}

source:
  url: https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"

requirements:
  host:
    - python ==3.6
  run:
    - python ==3.6
    - hmmer
    - biopython ==1.70
    - fasttree
    - numpy
    - scipy
    - networkx
    - scikit-learn ==0.19.1
    - dataclasses

test:
  commands:
    - 'bigscape.py --version'

about:
  home: https://github.com/medema-group/BiG-SCAPE
  license: GNU Affero v3
  summary: Biosynthetic Genes Similarity Clustering and Prospecting Engine.
