{% set version = "1.3.1" %}
{% set source_hash = "147d9fe9652f7c5f351bfc0eb012e06981986fb43bd6bdfe88a95c02eabc6573" %}
{% set osx_bin_hash = "878482cf2440edfe7a274f9ba22402a9e553f6237ec62a381abf696a688a21ee" %}

package:
  name: bowtie
  version: {{ version }}

source:
  url: https://github.com/BenLangmead/bowtie/archive/v{{ version }}.tar.gz  # [not osx]
  sha256: {{ source_hash }}   # [not osx]
  url: https://github.com/BenLangmead/bowtie/releases/download/v{{ version }}/bowtie-{{ version }}-macos-x86_64.zip  # [osx]
  sha256: {{ osx_bin_hash }}  # [osx]

build:
  skip: True  # [py<30]
  number: 2

requirements:
  build:
    - make                   # [not osx]
    - {{ compiler('cxx') }}  # [not osx]
  host:
    - python
    - tbb
    - tbb-devel
  run:
    - python
    - perl
    - tbb

test:
  commands:
    - bowtie --help
    - bowtie-align-l --help
    - bowtie-align-s --help
    - bowtie-build --help
    - bowtie-build-l --help
    - bowtie-build-s --help
    - bowtie-inspect --help
    - bowtie-inspect-l --help
    - bowtie-inspect-s --help

about:
  home: https://github.com/BenLangmead/bowtie
  license: Artistic-2.0-only
  summary: An ultrafast memory-efficient short read aligner

extra:
  identifiers:
    - biotools:bowtie
    - doi:10.1186/gb-2009-10-3-r25
