{% set version = "1.0.2" %}

package:
  name: hla-la
  version: {{ version }}

build:
  number: 0
  skip: true # [osx]

source:
  url: https://github.com/DiltheyLab/HLA-LA/archive/v{{ version }}.tar.gz
  sha256: ddcaecb2a96f62a98b69ab725589afe722a77df927e0e9830e013cfa49548d16
  folder: src

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
    - libboost =1.65
    - bamtools =2.5
    - perl-bio-db-hts
    - perl-bioperl
    - perl-bioperl-core
    - perl-bio-featureio
    - perl-text-levenshtein
    - perl-list-moreutils
  run:
    - libboost =1.65
    - bamtools =2.5
    - samtools =1.3
    - picard
    - bwa =0.7.12
    - mummer
    - perl-bio-db-hts
    - perl-bioperl
    - perl-bioperl-core
    - perl-bio-featureio
    - perl-text-levenshtein
    - perl-list-moreutils

about:
  home: https://github.com/DiltheyLab/HLA-LA
  license: GPL
  summary: HLA typing from short and long reads

test:
  commands:
    - HLA-LA.pl --testing 1
    - HLA-ASM.pl --testing 1

extra:
  identifiers:
    - biotools:hla-la
