{% set version = "0.3.0" %}
{% set github = "https://github.com/acidgenomics/r-acidsinglecell" %}

package:
  name: r-acidsinglecell
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 92d95d4c1077e04aaf3785f2ef40a6e030c9c2ad93fd79ed5a82e4989b0afdcb

build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-matrix
    - r-pipette >=0.8.0
    - r-scales
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-dropletutils
    - bioconductor-edger
    - bioconductor-scuttle
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-matrix
    - r-pipette >=0.8.0
    - r-scales
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-biocparallel
    - bioconductor-deseq2
    - bioconductor-dropletutils
    - bioconductor-edger
    - bioconductor-scuttle

test:
  commands:
    - $R -e "library('AcidSingleCell')"

about:
  home: https://r.acidgenomics.com/packages/acidsinglecell/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for single-cell RNA-seq analysis that extends the
    functionality of SingleCellExperiment.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
