{% set version = "1.1.1" %}
{% set sha256 = "95eb1913fccee0094992927ff7b453613b32181b58bb74454a0ec76f2dd4d889" %}

package:
  name: libssw
  version: {{ version }}

build:
  number: 0
  skip: True  # [py>=30 or osx]

source:
  url: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - make
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk
    - python
    - zlib
  run:
    - openjdk
    - python
    - zlib

test:
  commands:
    - test -e ${PREFIX}/include/ssw.h
    - test -e ${PREFIX}/include/ssw_cpp.h
    - ssw_test 2>&1 | grep ssw_test
    - pyssw.py -h
    - java -Djava.library.path=${PREFIX}/lib -jar ${PREFIX}/bin/ssw.jar -h

about:
  home: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library
  license: MIT
  summary: 'An SIMD Smith-Waterman C/C++/Python/Java Library for Use in Genomic Applications'
