{% set version = "0.8.1" %}
{% set github = "https://github.com/acidgenomics/r-acidgsea" %}

package:
  name: r-acidgsea
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 9e6d652d025f4d103b5469a22b509ab16ca8d09829e57a2fcec6584863b5affd

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-fgsea
    - bioconductor-genomeinfodb
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidbase
    - r-acidcli
    - r-acidexperiment
    - r-acidgenerics
    - r-acidgenomes
    - r-acidmarkdown
    - r-acidplots
    - r-acidplyr
    - r-deseqanalysis
    - r-ggplot2
    - r-goalie
    - r-pipette
    - r-sessioninfo
    - r-syntactic
    # Suggests:
    - bioconductor-biocparallel
    - r-basejump
    - r-knitr
    - r-rmarkdown
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-fgsea
    - bioconductor-genomeinfodb
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidbase
    - r-acidcli
    - r-acidexperiment
    - r-acidgenerics
    - r-acidgenomes
    - r-acidmarkdown
    - r-acidplots
    - r-acidplyr
    - r-deseqanalysis
    - r-ggplot2
    - r-goalie
    - r-pipette
    - r-sessioninfo
    - r-syntactic
    # Suggests:
    - bioconductor-biocparallel
    - r-basejump
    - r-knitr
    - r-rmarkdown

test:
  commands:
    - $R -e "library('AcidGSEA')"

about:
  home: https://r.acidgenomics.com/packages/acidgsea/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Parameterized fast gene set enrichment analysis.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
