package:
  name: alohomora
  version: "0.33"

source:
  fn: alohomora_v0.33-linux.tar.gz
  url: http://gmc.mdc-berlin.de/alohomora/alohomora_v0.33-linux.tar.gz
  md5sum: 891b521d012fbee827e2a2ea8eef3709
    

build:
  number: 0

  
requirements:
  build:
    - perl
    - zlib
    - dos2unix

  run:
    - perl
    - tk
    #- perl-cwd

#    imports:
 #     - Tk
  #    - Cwd
   #   - File::Copy
    #  - File::Basename

    
test:
  commands:
    - alohomora -h


about:
  home: http://gmc.mdc-berlin.de/alohomora/
  license: INDIVIDUAL
    # see: http://gmc.mdc-berlin.de/alohomora/legalities.txt
  summary: A tool designed to facilitate genome-wide linkage studies performed with high-density single nucleotide polymorphism (SNP) marker panels such as the Affymetrix GeneChip(R) Human Mapping 10K Array.
