{% set version = "2.0.3" %}

package:
  name: kaptive
  version: {{ version }}

source:
  url: https://github.com/katholt/Kaptive/archive/v{{ version }}.tar.gz
  sha256: 744ba757a75aea7513e67510434c6f2dbbe48e9fcf16ac4c92fe19192f65edb1

build:
  number: 0
  noarch: python
  # script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - biopython <1.78
    - numpy
    - blast >=2.3.0

test:
  commands:
    - kaptive.py -h

about:
  home: https://github.com/katholt/Kaptive
  license: GPL3
  license_file: LICENSE
  summary: Reports information about surface polysaccharide loci for Klebsiella and Acinetobacter baumannii genome assemblies
