{% set version = "2.0.1" %}

package:
  name: kaptive
  version: {{ version }}

source:
  url: https://github.com/katholt/Kaptive/archive/v{{ version }}.tar.gz
  sha256: a505b0c095e0e3fa81f2357c96c67fa2a70483c931596ed77401fd592bbfa3ba

build:
  number: 0
  noarch: python
  # script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
  run:
    - python >=3
    - biopython <1.78
    - numpy
    - blast >=2.3.0

test:
  commands:
    - kaptive.py -h

about:
  home: https://github.com/katholt/Kaptive
  license: GPL3
  license_file: LICENSE
  summary: Reports information about surface polysaccharide loci for Klebsiella and Acinetobacter baumannii genome assemblies
