{% set version = "0.4.0" %}

package:
  name: ananse
  version: {{ version }}

source:
  url: https://github.com/vanheeringen-lab/ANANSE/releases/download/v{{ version }}/ANANSE-{{ version }}.tar.gz
  sha256: 111e539038f9211bd8488f0ef36a32fb12b2044cd5747ed4fe224981a6e4bfa1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  
requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - adjusttext
    - dask
    - genomepy >=0.11.0
    - gimmemotifs >=0.17.1
    - biofluff >=3.0.4  # tmp: can be removed when gimme 0.17.1 build 1 is available
    - loguru
    - matplotlib-base >=2
    - networkx
    - numpy
    - openpyxl
    - pandas
    - pybedtools
    - pydot >=1.4.1   # required for networkx plots
    - pygraphviz >=1.7   # required for networkx plots
    - pyranges
    - pytables  # required for pandas.read_hfd()
    - scikit-learn
    - scipy >=0.9.0
    - seaborn
    - tqdm

test:
  imports:
    - ananse
  commands:
    - ananse -h
    - ananse binding -h
    - ananse network -h
    - ananse influence -h
    - ananse view -h
    - ananse plot -h

about:
  home: https://github.com/vanheeringen-lab/ANANSE
  license: MIT License
  license_file: LICENSE
  summary: 'ANANSE: ANalysis Algorithm for Networks Specified by Enhancers - Prediction of key transcription factors in cell fate determination using enhancer networks'
  license_family: MIT

extra:
  recipe-maintainers:
    - simonvh
  identifiers:
    - biotools:ananse
