{% set version = "0.6.1" %}
{% set github = "https://github.com/acidgenomics/r-goalie" %}

package:
  name: r-goalie
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 10acbe5ce03a1c700e21be5f555174e8282b3b96dcd290cb31b342455e59e54c
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base >=4.1
  run:
    - r-base >=4.1

test:
  commands:
    - $R -e "library('goalie')"

about:
  home: https://r.acidgenomics.com/packages/goalie/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Assertive check functions for defensive R programming.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
