{% set version = "0.6.4" %}
{% set github = "https://github.com/acidgenomics/r-goalie" %}

package:
  name: r-goalie
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: c4699182a7ab7218ba12b266cc0fff42018aa3d38d8ff1ada042baa8a88e4110
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base >=4.1
  run:
    - r-base >=4.1

test:
  commands:
    - $R -e "library('goalie')"

about:
  home: https://r.acidgenomics.com/packages/goalie/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Assertive check functions for defensive R programming.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
