{% set version = "0.6.3" %}
{% set github = "https://github.com/acidgenomics/r-goalie" %}

package:
  name: r-goalie
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: cc9dc29ad93a089371609d6f1d149ee0f388fcb829f2488358e1df6034c96f87
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    - r-base >=4.1
  run:
    - r-base >=4.1

test:
  commands:
    - $R -e "library('goalie')"

about:
  home: https://r.acidgenomics.com/packages/goalie/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Assertive check functions for defensive R programming.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
