{% set name = "perl-package-stash-xs" %}
{% set version = "0.30" %}
{% set sha256 = "26bad65c1959c57379b3e139dc776fbec5f702906617ef27cdc293ddf1239231" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/Package-Stash-XS-0.30.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - perl
    - perl-test-requires
    - perl-test-fatal
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Package::Stash::XS

about:
  home: http://metacpan.org/release/Package-Stash-XS
  license: perl_5
  summary: 'faster and more correct implementation of the Package::Stash API'
