{% set version = "0.16.0" %}
{% set github = "https://github.com/acidgenomics/r-basejump" %}

package:
  name: r-basejump
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: b696fe79c78b67be67c487a4af9047ac79bd82f9f2478d549a0f3d8c6cf9043c

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidmarkdown >=0.1.5
    - r-acidplyr >=0.2.0
    - r-acidsinglecell >=0.2.0
    - r-magrittr
    - r-matrix
    - r-pipette >=0.8.0
    - r-sessioninfo
    - r-stringr
    - r-syntactic >=0.5.1
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-biocio
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-singlecellexperiment
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidmarkdown >=0.1.5
    - r-acidplyr >=0.2.0
    - r-acidsinglecell >=0.2.0
    - r-magrittr
    - r-matrix
    - r-pipette >=0.8.0
    - r-sessioninfo
    - r-stringr
    - r-syntactic >=0.5.1

test:
  commands:
    - $R -e "library('basejump')"

about:
  home: https://r.acidgenomics.com/packages/basejump/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions for bioinformatics and R package development.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
