{% set name = "cazy_webscraper" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/HobnobMancer/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 834f47a983f847f82e670f4b57162abd851ade334aa42a79bde59f6f6f31a4b2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv --ignore-installed ."

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - beautifulsoup4
    - biopython
    - html5lib
    - lxml
    - mechanicalsoup
    - numpy
    - pandas
    - pyyaml
    - requests
    - sqlalchemy ==1.3.20
    - tqdm

test:
  imports:
    - scraper
  commands:
    - cazy_webscraper.py -h

about:
  home: https://hobnobmancer.github.io/cazy_webscraper/
  license: MIT
  license_file: LICENSE
  summary: 'The cazy_webscraper automates retrieval of protein data from the CAZy database.'
  license_family: MIT
