{% set version = "0.2.0" %}
{% set github = "https://github.com/acidgenomics/r-acidmarkdown" %}

package:
  name: r-acidmarkdown
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 0e59ebbeb17b8178282314afd707972cba7179644ec17efaeadc38c13df19fc2

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-goalie
    - r-knitr
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-goalie
    - r-knitr

test:
  commands:
    - $R -e "library('AcidMarkdown')"

about:
  home: https://r.acidgenomics.com/packages/acidmarkdown/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for extending the functionality of R Markdown.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
