{% set version = "0.2.1" %}
{% set github = "https://github.com/acidgenomics/r-acidmarkdown" %}

package:
  name: r-acidmarkdown
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 3ec1442e657f1dbb7280a5f000de7f60abfd940b7009e64036d605646b8e7066

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-goalie
    - r-knitr
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-goalie
    - r-knitr

test:
  commands:
    - $R -e "library('AcidMarkdown')"

about:
  home: https://r.acidgenomics.com/packages/acidmarkdown/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for extending the functionality of R Markdown.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
