{% set version = "0.4" %}

package:
  name: asqcan
  version: {{ version }}

source:
  url: https://github.com/bogemad/asqcan/archive/v{{ version }}.tar.gz
  sha256: d0abbba258f63ceeda73b71620c5cadd15ba15919df936c2b4b6e2fc87ceaafb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python <3
    - pip
  run:
    - python <3
    - parallel
    - fastqc
    - spades
    - quast
    - blobtools
    - blast
    - prokka

test:
  commands:
    - asqcan -h

about:
  home: https://github.com/bogemad/asqcan
  license: GPLv3
  summary: 'A combined pipeline for bacterial genome assembly, quality control and annotation'
  license_family: GPL
