{% set version = '0.8.1' %}
{% set github = "https://github.com/hbc/bcbioBase" %}

package:
  name: r-bcbiobase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 4364ccda28a9a6b4d6c50dd518bb8f088082a8f948279bad3cb084bd31fa22b6

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    - r-stringr
    - r-syntactic >=0.5.1
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidexperiment >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    - r-stringr
    - r-syntactic >=0.5.1

test:
  commands:
    - $R -e "library('bcbioBase')"

about:
  home: https://r.acidgenomics.com/packages/bcbiobase/
  dev_url: "{{ github }}"
  license: GPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Base functions and generics for bcbio R packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - hbc
    - mjsteinbaugh
