{% set version = "0.4.1" %}
{% set github = "https://github.com/acidgenomics/r-acidgenomes" %}

package:
  name: r-acidgenomes
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 6262457fd1bf1f8be329b9a09089707a94565fda766b402261373a5b4cf6a72c

build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-httr
    - r-pipette >=0.8.0
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biomart
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-ensembldb
    - bioconductor-genomicfeatures
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-httr
    - r-pipette >=0.8.0
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-annotationdbi
    - bioconductor-annotationhub
    - bioconductor-biomart
    - bioconductor-ensdb.hsapiens.v75
    - bioconductor-ensembldb
    - bioconductor-genomicfeatures

test:
  commands:
    - $R -e "library('AcidGenomes')"

about:
  home: https://r.acidgenomics.com/packages/acidgenomes/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit for downloading and processing genome annotations.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
