{% set name = "transit" %}
{% set version = "3.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mad-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3febe7c09a163214a8df7386af2c8a262d59d92cf74ade5625b890b0ea5665d7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  noarch: python
  
requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.16,<1.17
    - scipy >=1.2,<1.3
    - matplotlib-base >=3,<3.1
    - pillow >=6,<6.1
    - statsmodels >=0.9,<0.10

test:
  commands:
    - transit

about:
  home: http://github.com/mad-lab/transit
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: 'TRANSIT'
  description: |
    TRANSIT is a software that can be used to analyze Tn-Seq datasets.
    It includes various statistical calculations of essentiality of
    genes or genomic regions (including conditional essentiality
    between 2 conditions).
  dev_url: https://github.com/simongog/sdsl-lite
