{% set name = "phylodm" %}
{% set version = "2.0.3" %}
{% set sha256 = "81d61fdc3397f5934772d9f658dd16c26f505e992e7e7c23148c0bdcbe60edd3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py<37]

requirements:
  build:
    - rust >=1.40
  host:
    - python >=3.7
    - pip
    - setuptools
    - setuptools-rust
  run:
    - python >=3.7
    - numpy

test:
  imports:
    - phylodm
    - phylodm.pdm

about:
  home: https://github.com/aaronmussig/PhyloDM
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Efficient calculation of phylogenetic distance matrices.

extra:
  recipe-maintainers:
    - aaronmussig
  identifiers:
    - doi:10.5281/zenodo.3998716
