{% set name = "perl-compress-raw-zlib" %}
{% set version = "2.201" %}
{% set sha256 = "a1413b20b17893e604251ca52f259c2554639531f4d82ff573137135b5137c06" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Zlib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Compress::Raw::Zlib

about:
  home: http://metacpan.org/pod/Compress::Raw::Zlib
  license: perl_5
  summary: 'Basic utilities for writing tests.'
