{% set version = "0.3.0" %}
{% set github = "https://github.com/acidgenomics/r-acidplyr" %}

package:
  name: r-acidplyr
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: f277a887a52fb6076493c9d3203ff7f19f4e7ba244e60b19e6732e80fc26b25e
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    # Suggests:
    - bioconductor-iranges
    - r-dplyr
    - r-purrr
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    # Suggests:
    - bioconductor-iranges
    - r-dplyr
    - r-purrr

test:
  commands:
    - $R -e "library('AcidPlyr')"

about:
  home: https://r.acidgenomics.com/packages/acidplyr/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: A grammar of S4 class data manipulation.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
