{% set version = "0.6.3" %}
{% set github = "https://github.com/acidgenomics/r-acidbase" %}

package:
  name: r-acidbase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: ab1e02b774f46c1e36e029a8956ba4b6632af059bceb230c25807fb2ef036ccf
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-processx
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biocgenerics
    - bioconductor-s4vectors
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-processx

test:
  commands:
    - $R -e "library('AcidBase')"

about:
  home: https://r.acidgenomics.com/packages/acidbase/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Low-level base functions imported by Acid Genomics packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
