{% set version = "0.4.3" %}
{% set github = "https://github.com/acidgenomics/r-acidexperiment" %}

package:
  name: r-acidexperiment
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: f673924a0dc8c02b05033264181d2e4ff635d77c29d8d6657e82d23c10523fff

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.1.8
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    - r-scales
    - r-sessioninfo
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - r-matrix
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - r-acidbase >=0.5.0
    - r-acidcli >=0.1.8
    - r-acidgenerics >=0.6.0
    - r-acidgenomes >=0.3.0
    - r-acidplyr >=0.2.0
    - r-goalie >=0.6.0
    - r-pipette >=0.8.0
    - r-scales
    - r-sessioninfo
    - r-stringr
    - r-syntactic >=0.5.1
    # Suggests:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - r-matrix

test:
  commands:
    - $R -e "library('AcidExperiment')"

about:
  home: https://r.acidgenomics.com/packages/acidexperiment/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Toolkit to extend the functionality of SummarizedExperiment.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
