{% set version = "0.2.1" %}
{% set github = "https://github.com/acidgenomics/r-acidcli" %}

package:
  name: r-acidcli
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: ddbddf0e90b3aafb38490210be4266a3a4c6f175942d64db7bb961c10537197d

build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-cli >=3.2.0
    - r-crayon >=1.5.0
    - r-goalie >=0.6.0
  run:
    # Depends:
    - r-base >=4.1
    # Imports:
    - r-cli >=3.2.0
    - r-crayon >=1.5.0
    - r-goalie >=0.6.0

test:
  commands:
    - $R -e "library('AcidCLI')"

about:
  home: https://r.acidgenomics.com/packages/acidcli/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Interative R command line interface toolkit for Acid Genomics
    packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
