{% set version = "0.6.3" %}
{% set github = "https://github.com/acidgenomics/r-syntactic" %} 

package:
  name: r-syntactic
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 81c139eee1f85e34d9b6fe4fc65abe041a332107f6c8fe1ee5f548241005669e

build:
  noarch: generic
  number: 0

requirements:
  host:
      # Depends:
    - r-base >=4.1
      # Imports:
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-stringi
    - r-stringr
  run:
      # Depends:
    - r-base >=4.1
      # Imports:
    - r-acidbase >=0.5.0
    - r-acidcli >=0.2.0
    - r-acidgenerics >=0.6.0
    - r-goalie >=0.6.0
    - r-stringi
    - r-stringr

test:
  commands:
    - $R -e "library('syntactic')"

about:
  home: https://r.acidgenomics.com/packages/syntactic/
  dev_url: "{{ github }}"
  license: AGPL-3
  license_file: LICENSE
  license_family: GPL
  summary: Make syntactically valid names out of character vectors.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
